# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-11 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mysqldbmanager', '0002_mysqldbinfo_mysqldbname'),
    ]

    operations = [
        migrations.CreateModel(
            name='generalUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generalUserName', models.CharField(max_length=50)),
                ('generalUserPassword', models.CharField(max_length=50)),
                ('generalUserMail', models.CharField(max_length=50)),
                ('generalUserDatabase', models.ManyToManyField(to='mysqldbmanager.Mysqldbinfo')),
            ],
        ),
        migrations.CreateModel(
            name='userRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userRole', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='generaluser',
            name='generalUserRole',
            field=models.ManyToManyField(to='usermanager.userRole'),
        ),
    ]
