# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-11 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generaluser',
            name='generalUserDatabase',
            field=models.ManyToManyField(to='mysqldbmanager.Mysqldbinfo'),
        ),
    ]
