# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-04 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mysqldbinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mysqldbalias', models.CharField(max_length=50)),
                ('mysqldbuser', models.CharField(max_length=50)),
                ('mysqldbpasswd', models.CharField(max_length=50)),
                ('mysqldbhost', models.CharField(max_length=50)),
                ('mysqldbport', models.CharField(max_length=20)),
            ],
        ),
    ]
