# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-11 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysqldbmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysqldbinfo',
            name='mysqldbname',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
