# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-11 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysqldbmanager', '0002_mysqldbinfo_mysqldbname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysqldbinfo',
            name='mysqldbname',
            field=models.CharField(max_length=50),
        ),
    ]
